INSERT INTO config (setting, value) VALUES
  ('attack_mitigation_time', '+30 minutes'),
  ('attempts_before_ban', '30'),
  ('bcrypt_cost', '10'),
  ('cookie_forget', '+60 minutes'),
  ('cookie_remember', '+1 month'),
  ('email', '1'),
  ('email_send_disguise', '4'),
  ('site_name', 'Style Guide'),
  ('site_activation_page', 'activate'),
  ('site_password_reset_page', 'reset-password'),
  ('site_timezone', 'America/Denver'),
  ('site_key', 'fghuior.)/!/jdUkd8s2!7HVHG7777ghg'),
  ('verify_email_max_length', '254'),
  ('verify_email_min_length', '5'),
  ('verify_email_use_banlist', '1'),
  ('verify_password_min_length', '3'),
  ('request_key_expiration', '+60 minutes');